[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/drive/1OnX3Bb-VQtD0g8usQmE0_UF5Y6A03A7l)



<a name='0'></a>
# Аналитика с Pandas


* [Базовые инструменты:](#1)

     * [A. Series и DataFrames](#1-1)
     * [B. Индексация и Фильтры](#1-2)
     * [C. Оаработка пустот](#1-3)
     * [D. Базовые операции и функции](#1-4)
     * [E. Агрегационные функции](#1-5)
     * [F. Группировка](#1-6)
     * [G. Merge и Concatenate](#1-7)
     * [H. Работа с csv и excel](#1-8)

<a name='1'></a>
## 1. Базовые инструменты

<a name='1-1'></a>
### A. Series и DataFrames

pd.Series и pd.DataFrames - структуры данных Pandas

In [4]:
import numpy as np
import pandas as pd

#### Создание Series

pd.Series - это и Python list, и dict (словарь), и array (массив).

In [5]:
# pd.Series как Python list

num_list = [1,2,3,4,5]

pd.Series(num_list)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [6]:
week_days = ['Mon','Tues','Wed','Thur','Fri']

pd.Series(week_days, index=["a", "b", "c", "d", "e"])

a     Mon
b    Tues
c     Wed
d    Thur
e     Fri
dtype: object

In [7]:
# pd.Series как dict

countries_code = { 1:"United States",
                 91:"India",
                 49:"Germany",
                 86:"China",
                250:"Rwanda"}

pd.Series(countries_code)

1      United States
91             India
49           Germany
86             China
250           Rwanda
dtype: object

In [8]:
d = {1:'a', 2:'b', 3:'c', 4:'d'}
pd.Series(d)

1    a
2    b
3    c
4    d
dtype: object

In [9]:
# pd.Series как array (массив)

arr = np.array ([1, 2, 3, 4, 5])
pd.Series(arr)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [10]:
pd.Series(arr, index=['a', 'b', 'c', 'd', 'e'])

a    1
b    2
c    3
d    4
e    5
dtype: int64

#### Создание DataFrame

pd.Series - это и и dict (словарь), и 2D array (2-мерный массив), и pd.Series.

In [11]:
# pd.DataFrame как dict

countries = {'Name': ['USA', 'India', 'German', 'Rwanda'],

             'Codes':[1, 91, 49, 250] }

pd.DataFrame(countries)

     Name  Codes
0     USA      1
1   India     91
2  German     49
3  Rwanda    250

In [12]:
# pd.DataFrame как 2d массив

array_2d = np.array ([[1,2,3], [4,5,6], [7,8,9]])

pd.DataFrame(array_2d, columns = ['column 1', 'column 2', 'column 3'])

   column 1  column 2  column 3
0         1         2         3
1         4         5         6
2         7         8         9

In [13]:
# pd.DataFrame как pd.Series

countries_code = { "United States": 1,
                 "India": 91,
                 "Germany": 49,
                 "China": 86,
                 "Rwanda":250}

pd_series = pd.Series (countries_code)

pd.Series(countries_code)

df = pd.DataFrame(pd_series, columns = ['Codes'])
df

               Codes
United States      1
India             91
Germany           49
China             86
Rwanda           250

In [14]:
# Добавление и удаление столбцов

df ['Population'] = [100, 450, 575, 5885, 533]
display(df)
display(df.drop('Population', axis =1))

               Codes  Population
United States      1         100
India             91         450
Germany           49         575
China             86        5885
Rwanda           250         533

               Codes
United States      1
India             91
Germany           49
China             86
Rwanda           250

In [16]:
# Обращение к столбцам, индексам и ключам 
print('столбцы \n')
display(df.columns)

print('ключи \n')
display(df.keys)

print('индексы \n')
display(df.index)

столбцы

Index(['Codes', 'Population'], dtype='object')

ключи

<bound method NDFrame.keys of                Codes  Population
United States      1         100
India             91         450
Germany           49         575
China             86        5885
Rwanda           250         533>

индексы

Index(['United States', 'India', 'Germany', 'China', 'Rwanda'], dtype='object')

<a name='1-2'></a>
### B. Индексация и Фильтры

Индексация и фильтрация одинакова для pd.Series и pd.DataFrame

In [17]:
countries = {'Name': ['USA', 'India', 'German', 'Rwanda'],

             'Codes':[1, 91, 49, 250] }

df = pd.DataFrame(countries, index=['a', 'b', 'c', 'd'])
df

     Name  Codes
a     USA      1
b   India     91
c  German     49
d  Rwanda    250

In [23]:
# Обращение к столбцам
display(df['Name'])

display(df.Name)

display(df['Codes'])

## обращение к нескольким столбцам может быть только через список столбцов

display(df[['Name', 'Codes']])

a       USA
b     India
c    German
d    Rwanda
Name: Name, dtype: object

a       USA
b     India
c    German
d    Rwanda
Name: Name, dtype: object

a      1
b     91
c     49
d    250
Name: Codes, dtype: int64

     Name  Codes
a     USA      1
b   India     91
c  German     49
d  Rwanda    250

In [24]:
# Обращение к строкам
display(df[0:2])

display(df.loc['a'])

display(df.loc['b':'d'])

display(df [:'b'])

display(df.iloc[2])

display(df.iloc[1:3])

display(df.iloc[2:])

    Name  Codes
a    USA      1
b  India     91

Name     USA
Codes      1
Name: a, dtype: object

     Name  Codes
b   India     91
c  German     49
d  Rwanda    250

    Name  Codes
a    USA      1
b  India     91

Name     German
Codes        49
Name: c, dtype: object

     Name  Codes
b   India     91
c  German     49

     Name  Codes
c  German     49
d  Rwanda    250

### Фильтрация

In [25]:
display(df[df['Codes'] ==49])

display(df[df['Codes'] < 250])

display(df[df['Name'] =='USA'])

display(df[(df['Codes'] == 91 ) & (df['Name'] == 'India')])

     Name  Codes
c  German     49

     Name  Codes
a     USA      1
b   India     91
c  German     49

  Name  Codes
a  USA      1

    Name  Codes
b  India     91

In [26]:
# isin() - проверка на вхождение в список или в ключи списка
sample_codes_names=[1,3,250, 'USA', 'India', 'England']

display(df.isin(sample_codes_names))

sample_codes_names = {'Codes':[1,3,250], 'Name':['USA', 'India', 'England']}

display(df.isin(sample_codes_names))

    Name  Codes
a   True   True
b   True  False
c  False  False
d  False   True

    Name  Codes
a   True   True
b   True  False
c  False  False
d  False   True

In [28]:
df2 = pd.DataFrame(np.array ([[1,2,3], [4,5,6], [7,8,9]]),
                   columns = ['column 1', 'column 2', 'column 3'])

df2

   column 1  column 2  column 3
0         1         2         3
1         4         5         6
2         7         8         9

In [29]:
df2.isin([0,3,4,5,7])

   column 1  column 2  column 3
0     False     False      True
1      True      True     False
2      True     False     False

In [30]:
df2[df2 > 4]

   column 1  column 2  column 3
0       NaN       NaN       NaN
1       NaN       5.0       6.0
2       7.0       8.0       9.0

In [31]:
df2.where(df2 > 4)

   column 1  column 2  column 3
0       NaN       NaN       NaN
1       NaN       5.0       6.0
2       7.0       8.0       9.0

In [32]:
# с where можно заменять занчения при выполнении условия
display(df2.where(df2 > 4, 0))

df2[df2 <= 4] = 0
display(df2)

   column 1  column 2  column 3
0         0         0         0
1         0         5         6
2         7         8         9

   column 1  column 2  column 3
0         0         0         0
1         0         5         6
2         7         8         9

### Итерирование

```
df.items(), df.iteritems() - по паре (column name, Series)
DataFrame.iterrows() - по паре (column name, Series) как строка 
DataFrame.itertuples([index, name]) - по строкам как именованные кортежи (tuple)
```

In [33]:
# Итерирование по паре (column name, Series)

for col_name, content in df2.items():
    print(col_name)
    print(content)
    
# for col_name, content in df2.iteritems():
#     print(col_name)
#     print(content)

column 1
0    0
1    0
2    7
Name: column 1, dtype: int64
column 2
0    0
1    5
2    8
Name: column 2, dtype: int64
column 3
0    0
1    6
2    9
Name: column 3, dtype: int64

In [ ]:
# Итерирование по паре (column name, Series) как строка 

for row in df2.iterrows():
    print(row)

(0, column 1    0
column 2    0
column 3    0
Name: 0, dtype: int64)
(1, column 1    0
column 2    5
column 3    6
Name: 1, dtype: int64)
(2, column 1    7
column 2    8
column 3    9
Name: 2, dtype: int64)

In [ ]:
# Итерирование по строкам как именованные кортежи (tuple)

for row in df2.itertuples():
    print(row)

Pandas(Index=0, _1=0, _2=0, _3=0)
Pandas(Index=1, _1=0, _2=5, _3=6)
Pandas(Index=2, _1=7, _2=8, _3=9)

<a name='1-3'></a>
### C. Обработка пропущенных значений

Пропущенные значения могут быть проигнорированы, удалены или заполнены

In [34]:
df3 = pd.DataFrame(np.array ([[1,2,3], [4,np.nan,6], [7,np.nan,np.nan]]),
                   columns = ['column 1', 'column 2', 'column 3'])

#### Checking Missing values

In [35]:
# Проверка на пустоты 

df3.isnull()

   column 1  column 2  column 3
0     False     False     False
1     False      True     False
2     False      True      True

In [36]:
# Число пустот

df3.isnull().sum()

column 1    0
column 2    2
column 3    1
dtype: int64

In [37]:
# Проверка на непустоты

df3.notna()

   column 1  column 2  column 3
0      True      True      True
1      True     False      True
2      True     False     False

In [38]:
# Число заполненных полей
df3.notna().sum()

column 1    3
column 2    1
column 3    2
dtype: int64

#### Удаление пустот

In [39]:
# Удаление строк и столбцов с пустотами
df3.dropna()

   column 1  column 2  column 3
0       1.0       2.0       3.0

In [ ]:
# Удаление поля с пустотой в столбце

df3['column 3'].dropna()

0    3.0
1    6.0
Name: column 3, dtype: float64

In [40]:
# Удаление столбцов и строок с пустотами

df3.dropna(axis=1)

# df3.dropna(axis=0)

   column 1
0       1.0
1       4.0
2       7.0

#### Заполнение пустот

In [41]:
# Заполнение пустот 10

df3.fillna(10)

   column 1  column 2  column 3
0       1.0       2.0       3.0
1       4.0      10.0       6.0
2       7.0      10.0      10.0

In [42]:
# Заполнение пустот fillme

df3.fillna('fillme')

   column 1 column 2 column 3
0       1.0      2.0      3.0
1       4.0   fillme      6.0
2       7.0   fillme   fillme

In [43]:
# Заполнение предыдущим (ffill) или следующим (bfill) значением

df3.fillna(method='ffill')

# df3.fillna(method='bfill')

   column 1  column 2  column 3
0       1.0       2.0       3.0
1       4.0       2.0       6.0
2       7.0       2.0       6.0

<a name='1-4'></a>
### D. Базовые операции и функции

In [45]:
df4 = pd.DataFrame({'Product Name':['Shirt','Boot','Bag'],
              'Order Number':[45,56,64],
              'Total Quantity':[10,5,9]},
              columns = ['Product Name', 'Order Number', 'Total Quantity'])

In [46]:
# ПОлучение свода по DataFrame

df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Product Name    3 non-null      object
 1   Order Number    3 non-null      int64
 2   Total Quantity  3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 200.0+ bytes

In [47]:
# Вывод первых/последних n строк

df4.head(1)
# df4.tail(1)

  Product Name  Order Number  Total Quantity
0        Shirt            45              10

In [48]:
# Вывод размера DataFrame

df4.size, df4.shape, (df4.shape[0], df4.shape[1])

(9, (3, 3), (3, 3))

#### Уникальные значения

In [49]:
# Список уникальных значений

df4['Product Name'].unique()

array(['Shirt', 'Boot', 'Bag'], dtype=object)

In [50]:
# Число уникальных значений
df4['Product Name'].nunique()

3

In [51]:
# Число появленний каждого значения в столбце

df4['Product Name'].value_counts()

Shirt    1
Boot     1
Bag      1
Name: Product Name, dtype: int64

#### Применение функций

In [52]:
def double_quantity(x):
    """Квадрат числа"""
    return x * x

In [53]:
df4['Total Quantity'].apply(double_quantity)

0    100
1     25
2     81
Name: Total Quantity, dtype: int64

In [54]:


df5 = pd.DataFrame([[1,2], [4,5]], columns=['col1', 'col2'])

df5.applymap(lambda x: x**2)

   col1  col2
0     1     4
1    16    25

#### Сортировка

In [ ]:
# Сортировка по полю 'Order Number'

df4.sort_values(['Order Number'])

  Product Name  Order Number  Total Quantity
0        Shirt            45              10
1         Boot            56               5
2          Bag            64               9

In [ ]:
df4.sort_values(['Order Number'], ascending=False)

  Product Name  Order Number  Total Quantity
2          Bag            64               9
1         Boot            56               5
0        Shirt            45              10

<a name='1-5'></a>
### E. Aggregation Methods

In [ ]:
df4

  Product Name  Order Number  Total Quantity
0        Shirt            45              10
1         Boot            56               5
2          Bag            64               9

In [55]:
# Вывод статистик

df4.describe()

       Order Number  Total Quantity
count      3.000000        3.000000
mean      55.000000        8.000000
std        9.539392        2.645751
min       45.000000        5.000000
25%       50.500000        7.000000
50%       56.000000        9.000000
75%       60.000000        9.500000
max       64.000000       10.000000

In [ ]:
# Транспонирование (поворот) DataFrame
df4.describe().transpose()

                count  mean       std   min   25%   50%   75%   max
Order Number      3.0  55.0  9.539392  45.0  50.5  56.0  60.0  64.0
Total Quantity    3.0   8.0  2.645751   5.0   7.0   9.0   9.5  10.0

In [ ]:
# Определение моды, среднего, медианы, максимума, минимума, произведения и десперсии

df4['Total Quantity'].mode()
# df4['Total Quantity'].mean()
# df4['Total Quantity'].median()
# df4['Total Quantity'].max()
# df4['Total Quantity'].min()
# df4['Total Quantity'].prod()
# df4['Total Quantity'].std()

0     5
1     9
2    10
dtype: int64

<a name='1-6'></a>
### F. Группировка

In [ ]:
df4 = pd.DataFrame({'Product Name':['Shirt','Boot','Bag', 'Ankle', 'Pullover', 'Boot', 'Ankle', 'Tshirt', 'Shirt'],
              'Order Number':[45,56,64, 34, 67, 56, 34, 89, 45],
              'Total Quantity':[10,5,9, 11, 11, 8, 14, 23, 10]},
              columns = ['Product Name', 'Order Number', 'Total Quantity'])

In [ ]:
df4

  Product Name  Order Number  Total Quantity
0        Shirt            45              10
1         Boot            56               5
2          Bag            64               9
3        Ankle            34              11
4     Pullover            67              11
5         Boot            56               8
6        Ankle            34              14
7       Tshirt            89              23
8        Shirt            45              10

In [ ]:
# Оценка агрегатов (среднего, мин., макс., суммы) по полю 'Product Name'

df4.groupby('Product Name').mean()

# df4.groupby('Product Name').sum()
# df4.groupby('Product Name').min()
# df4.groupby('Product Name').max()

In [56]:
# Оценка агрегатов (среднего, мин., макс., суммы) по нескольким полям 'Product Name'
df4.groupby(['Product Name', 'Order Number']).max()

# df4.groupby(['Product Name', 'Order Number']).sum()
# df4.groupby(['Product Name', 'Order Number']).min()
# df4.groupby(['Product Name', 'Order Number']).max()

In [57]:
# Совокупность агр. функций
df4.groupby('Product Name').aggregate(['min', 'max', 'sum'])

             Order Number         Total Quantity
                      min max sum            min max sum
Product Name
Bag                    64  64  64              9   9   9
Boot                   56  56  56              5   5   5
Shirt                  45  45  45             10  10  10

<a name='1-7'></a>
### G. Merge и Concatenate

#### Concatenate

In [58]:
df1 = pd.DataFrame({'Col1':['A','B','C'],
                   'Col2':[1,2,3]},
                   index=['a','b','c'])

df2 = pd.DataFrame({'Col1':['D','E','F'],
                   'Col2':[4,5,6]},
                   index=['d','e','f'])


df3 = pd.DataFrame({'Col1':['G','I','J'],
                   'Col2':[7,8,9]},
                   index=['g', 'i','j'])

In [59]:
# Concatenate, append - складывание таблицы поверх другого

pd.concat([df1, df2, df3])
# df1.append([df2, df3])

  Col1  Col2
a    A     1
b    B     2
c    C     3
d    D     4
e    E     5
f    F     6
g    G     7
i    I     8
j    J     9

In [63]:
# складывание таблицы поверх другого вдоль строки/столбцов
pd.concat([df1, df2, df3], axis=1)

  Col1  Col2 Col1  Col2 Col1  Col2
a    A   1.0  NaN   NaN  NaN   NaN
b    B   2.0  NaN   NaN  NaN   NaN
c    C   3.0  NaN   NaN  NaN   NaN
d  NaN   NaN    D   4.0  NaN   NaN
e  NaN   NaN    E   5.0  NaN   NaN
f  NaN   NaN    F   6.0  NaN   NaN
g  NaN   NaN  NaN   NaN    G   7.0
i  NaN   NaN  NaN   NaN    I   8.0
j  NaN   NaN  NaN   NaN    J   9.0

#### Merge
Работает так же как в SQL Join (left, roght, outer, inner, cross)

In [64]:
df1 = pd.DataFrame({'Name': ['Joe', 'Joshua', 'Jeanne', 'David'],
                        'Role': ['Manager', 'Developer', 'Engineer', 'Scientist']})

df2 = pd.DataFrame({'Name': ['David', 'Joshua', 'Joe', 'Jeanne'],
'Year Hired': [2018, 2017, 2020, 2018]})

df3 = pd.DataFrame({'Name': ['David', 'Joshua', 'Joe', 'Jeanne'],
'No of Leaves': [15, 3, 10, 12]})

In [65]:
pd.merge(df1, df2)

     Name       Role  Year Hired
0     Joe    Manager        2020
1  Joshua  Developer        2017
2  Jeanne   Engineer        2018
3   David  Scientist        2018

In [66]:
pd.merge(df1, df2, how='inner', on="Name")

     Name       Role  Year Hired
0     Joe    Manager        2020
1  Joshua  Developer        2017
2  Jeanne   Engineer        2018
3   David  Scientist        2018

In [67]:
df1 = pd.DataFrame({'col1': ['K0', 'K0', 'K1', 'K2'],
                     'col2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3']})

df2 = pd.DataFrame({'col1': ['K0', 'K1', 'K1', 'K2'],
                               'col2': ['K0', 'K0', 'K0', 'K0'],
                                  'C': ['C0', 'C1', 'C2', 'C3'],
                                  'D': ['D0', 'D1', 'D2', 'D3']})

In [68]:
pd.merge(df1, df2, how='inner', on=['col1', 'col2'])

  col1 col2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

In [69]:
pd.merge(df1, df2, how='outer', on=['col1', 'col2'])

  col1 col2    A    B    C    D
0   K0   K0   A0   B0   C0   D0
1   K0   K1   A1   B1  NaN  NaN
2   K1   K0   A2   B2   C1   D1
3   K1   K0   A2   B2   C2   D2
4   K2   K1   A3   B3  NaN  NaN
5   K2   K0  NaN  NaN   C3   D3

In [70]:
pd.merge(df1, df2, how='left')

  col1 col2   A   B    C    D
0   K0   K0  A0  B0   C0   D0
1   K0   K1  A1  B1  NaN  NaN
2   K1   K0  A2  B2   C1   D1
3   K1   K0  A2  B2   C2   D2
4   K2   K1  A3  B3  NaN  NaN

In [71]:
pd.merge(df1, df2, how='right')

  col1 col2    A    B   C   D
0   K0   K0   A0   B0  C0  D0
1   K1   K0   A2   B2  C1  D1
2   K1   K0   A2   B2  C2  D2
3   K2   K0  NaN  NaN  C3  D3

<a name='1-8'></a>
### H. Работа с CSV и Excel

In [ ]:
# Скачаем данные

!curl -O https://raw.githubusercontent.com/nyandwi/public_datasets/master/housing.csv

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1390k  100 1390k    0     0   409k      0  0:00:03  0:00:03 --:--:--  409k

In [72]:
data = pd.read_csv('predict_house_price_training_data.csv')

In [73]:
data.head()

,Целевая.Цена,Спальни,Ванные,Жилая площадь,Общая площадь,Количество этажей,Вид на воду,Просмотрены ранее,Состояние,Оценка риелтора,Площадь без подвала,Площадь подвала,Год постройки,Год реновации,Широта,Долгота
0,830000,5,"3,5",3490,21780,2,0,0,3,8,3490,0,1996,0,"47,6707","-122,144"
1,385000,4,"1,75",2360,7620,1,0,0,4,7,1180,1180,1955,0,"47,5278","-122,345"
2,610000,6,"2,75",2040,8560,1,0,2,4,7,1100,940,1961,0,"47,616","-122,115"
3,550000,3,"1,75",1940,8376,1,0,0,4,8,1290,650,1963,0,"47,5586","-122,173"
4,1300000,3,"2,75",3450,5350,"1,5",0,3,4,9,2590,860,1925,0,"47,6389","-122,407"

In [74]:
type(data)

pandas.core.frame.DataFrame

In [75]:
## Запись в csv

data.to_csv('tmp.csv', index=False)

In [76]:
## Запись в Excel

data.to_excel('tmp.xlsx', index=False)

<ipython-input-76-0c1ee3ca266d>:3: UserWarning: Pandas requires version '1.4.3' or newer of 'xlsxwriter' (version '1.3.8' currently installed).
  data.to_excel('tmp.xlsx', index=False)

In [77]:
## Чтение из excel

excel_data = pd.read_excel('tmp.xlsx')

In [78]:

excel_data.head()

,Целевая.Цена,Спальни,Ванные,Жилая площадь,Общая площадь,Количество этажей,Вид на воду,Просмотрены ранее,Состояние,Оценка риелтора,Площадь без подвала,Площадь подвала,Год постройки,Год реновации,Широта,Долгота
0,830000,5,"3,5",3490,21780,2,0,0,3,8,3490,0,1996,0,"47,6707","-122,144"
1,385000,4,"1,75",2360,7620,1,0,0,4,7,1180,1180,1955,0,"47,5278","-122,345"
2,610000,6,"2,75",2040,8560,1,0,2,4,7,1100,940,1961,0,"47,616","-122,115"
3,550000,3,"1,75",1940,8376,1,0,0,4,8,1290,650,1963,0,"47,5586","-122,173"
4,1300000,3,"2,75",3450,5350,"1,5",0,3,4,9,2590,860,1925,0,"47,6389","-122,407"

# Задача:

Найдите самую выгодную для покупки квартиру в пересчете руб. на кв. м. среди квартир с, минимум, 2 спальнями, ванной не меньше 2 кв. м., и чтобы в сумме оценка состояния и оценка риелтора была больше 12